vim.keymap.set("n", "<leader><leader>", function() Snacks.picker.files() end)
vim.keymap.set("n", "<leader>ff", function() Snacks.picker.grep() end)
vim.keymap.set("n", "<leader>fl", function() Snacks.picker.lines() end)
vim.keymap.set("n", "<leader>fb", function() Snacks.picker.buffers() end)
vim.keymap.set("n", "<leader>fd", function() Snacks.picker.diagnostics() end)
vim.keymap.set("n", "<leader>fn", function() Snacks.picker.notifications() end)
vim.keymap.set("n", "<leader>nh", function() Snacks.notifier.show_history() end)
vim.keymap.set("n", "<leader>nd", function() Snacks.notifier.hide() end)
vim.keymap.set("n", "<leader>tf", function() Snacks.terminal.toggle(nil, { win = { style = "float" } }) end)
vim.keymap.set("n", "<leader>th", function() Snacks.terminal.toggle(nil, { win = { style = "split", position = "bottom", height = 0.3 } }) end)
vim.keymap.set("n", "<leader>tt", function() Snacks.terminal.toggle() end)
vim.keymap.set("n", "[d", function() vim.diagnostic.jump({ count = -1 }) end)
vim.keymap.set("n", "]d", function() vim.diagnostic.jump({ count = 1 }) end)
vim.keymap.set("n", "gl", vim.diagnostic.open_float)
vim.keymap.set("n", "<leader>s", "<cmd>w<CR>")
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>")

vim.keymap.set('n', '<leader>e', function() Snacks.explorer() end)
vim.keymap.set('n', '<leader>o', function() Snacks.explorer({ focus_file = vim.api.nvim_buf_get_name(0) }) end)
vim.keymap.set('n', '<leader>gg', function() Snacks.lazygit() end)
vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set('n', '<leader>/', 'gcc', { remap = true })
vim.keymap.set('v', '<leader>/', 'gc', { remap = true })
vim.keymap.set('n', '<leader>fr', function() require('grug-far').open({ prefills = { paths = vim.fn.expand('%') } }) end)
vim.keymap.set('n', '<leader>fR', function() require('grug-far').open() end)
vim.keymap.set('n', '<leader>\\', '<cmd>vsplit<CR>')
vim.keymap.set('n', '<leader>-', '<cmd>split<CR>')
vim.keymap.set('n', '<leader>ya', '<cmd>%y+<CR>')
vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')

local opts = { noremap = true, silent = true }

vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", opts)
vim.keymap.set("n", "<F12>", function() Snacks.picker.lsp_references() end, opts)
vim.keymap.set("n", "<F2>", vim.lsp.buf.rename, opts)
vim.keymap.set("n", "<Leader>fo", function()
	vim.lsp.buf.code_action({
		context = { only = { "source.organizeImports" }, diagnostics = {} },
		apply = true,
	})
	vim.lsp.buf.format()
end, opts)

-- Markdown
vim.keymap.set("n", "<leader>mp", "<cmd>MarkdownPreviewToggle<CR>", opts)

-- DAP
local dap = require('dap')
local dapui = require('dapui')
vim.keymap.set("n", "<F5>", dap.continue, opts)
vim.keymap.set("n", "<F10>", dap.step_over, opts)
vim.keymap.set("n", "<F11>", dap.step_into, opts)
vim.keymap.set("n", "<S-F11>", dap.step_out, opts)
local pb = require('persistent-breakpoints.api')
vim.keymap.set("n", "<leader>db", pb.toggle_breakpoint, opts)
vim.keymap.set("n", "<leader>dB", function() pb.set_conditional_breakpoint(vim.fn.input('Condition: ')) end, opts)
vim.keymap.set("n", "<leader>dC", pb.clear_all_breakpoints, opts)
vim.keymap.set("n", "<leader>dr", dap.restart, opts)
vim.keymap.set("n", "<leader>dx", dap.terminate, opts)
vim.keymap.set("n", "<leader>du", dapui.toggle, opts)
vim.keymap.set("n", "<leader>de", dapui.eval, opts)
vim.keymap.set("v", "<leader>de", dapui.eval, opts)
