# Префікс
unbind C-b
set -g prefix §
bind § send-prefix

# Базові налаштування
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "tmux-256color"
set-environment -g PATH "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
set -ga terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 10
set -g history-limit 50000
setw -g mode-keys vi

# Спліти з поточної директорії
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload конфіга
bind r source-file ~/.tmux.conf \; display "Reloaded"

# Vim-style навігація
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Copy-mode біндінги як в vim
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi r send-keys -X rectangle-toggle

# Плагіни
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'erikw/tmux-dark-notify'
#set -g @continuum-restore 'on'

set -g @dark-notify-theme-path-light '$HOME/.dotfiles/tmux/statusbar-light.conf'
set -g @dark-notify-theme-path-dark '$HOME/.dotfiles/tmux/statusbar-dark.conf'

run '~/.tmux/plugins/tpm/tpm'
